enum Type {
   FETCH_START = 'FETCH_START',
   FETCH_QUIZ_LIST_SUCCESS = 'FETCH_QUIZ_LIST_SUCCESS',
   FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS',
   FETCH_ERROR = 'FETCH_ERROR',

   SET_QUIZ_NAME = 'SET_QUIZ_NAME',
   UPDATE_RESULTS = 'UPDATE_RESULTS',
   SET_QUIZ_TIME = 'SET_QUIZ_TIME',
   SHOW_RESULTS = 'SHOW_RESULTS',
   GOTO_NEXT_QUESTION = 'GOTO_NEXT_QUESTION',
   RESTART_QUIZ = 'RESTART_QUIZ',

   UPDATE_QUIZ = 'UPDATE_QUIZ',
   RESET_CREATOR = 'RESET_CREATOR',

   AUTH_SUCCESS = 'AUTH_SUCCESS',
   AUTH_SIGN_OUT = 'AUTH_SIGN_OUT'
}

export default Type
