enum Type {
   FETCH_START = 'FETCH_START',
   FETCH_QUIZ_LIST_SUCCESS = 'FETCH_QUIZ_LIST_SUCCESS',
   FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS',
   FETCH_ERROR = 'FETCH_ERROR',

   UPDATE_RESULTS = 'UPDATE_RESULTS',
   SHOW_RESULTS = 'SHOW_RESULTS',
   GOTO_NEXT_QUESTION = 'GOTO_NEXT_QUESTION',
   RESTART_QUIZ = 'RESTART_QUIZ'
}

export default Type
